/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/samer/catkin_ws/src/pebble/srv/callMenu.srv
 *
 */


#ifndef PEBBLE_MESSAGE_CALLMENU_H
#define PEBBLE_MESSAGE_CALLMENU_H

#include <ros/service_traits.h>


#include <pebble/callMenuRequest.h>
#include <pebble/callMenuResponse.h>


namespace pebble
{

struct callMenu
{

typedef callMenuRequest Request;
typedef callMenuResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct callMenu
} // namespace pebble


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pebble::callMenu > {
  static const char* value()
  {
    return "22e4bc82a017518e6f1eda9e545219e7";
  }

  static const char* value(const ::pebble::callMenu&) { return value(); }
};

template<>
struct DataType< ::pebble::callMenu > {
  static const char* value()
  {
    return "pebble/callMenu";
  }

  static const char* value(const ::pebble::callMenu&) { return value(); }
};


// service_traits::MD5Sum< ::pebble::callMenuRequest> should match 
// service_traits::MD5Sum< ::pebble::callMenu > 
template<>
struct MD5Sum< ::pebble::callMenuRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pebble::callMenu >::value();
  }
  static const char* value(const ::pebble::callMenuRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pebble::callMenuRequest> should match 
// service_traits::DataType< ::pebble::callMenu > 
template<>
struct DataType< ::pebble::callMenuRequest>
{
  static const char* value()
  {
    return DataType< ::pebble::callMenu >::value();
  }
  static const char* value(const ::pebble::callMenuRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pebble::callMenuResponse> should match 
// service_traits::MD5Sum< ::pebble::callMenu > 
template<>
struct MD5Sum< ::pebble::callMenuResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pebble::callMenu >::value();
  }
  static const char* value(const ::pebble::callMenuResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pebble::callMenuResponse> should match 
// service_traits::DataType< ::pebble::callMenu > 
template<>
struct DataType< ::pebble::callMenuResponse>
{
  static const char* value()
  {
    return DataType< ::pebble::callMenu >::value();
  }
  static const char* value(const ::pebble::callMenuResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PEBBLE_MESSAGE_CALLMENU_H
