/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/samer/catkin_ws/src/pebble/srv/getMenu.srv
 *
 */


#ifndef PEBBLE_MESSAGE_GETMENU_H
#define PEBBLE_MESSAGE_GETMENU_H

#include <ros/service_traits.h>


#include <pebble/getMenuRequest.h>
#include <pebble/getMenuResponse.h>


namespace pebble
{

struct getMenu
{

typedef getMenuRequest Request;
typedef getMenuResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct getMenu
} // namespace pebble


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pebble::getMenu > {
  static const char* value()
  {
    return "ccba9f143bac9e35d9302ade4ff33f30";
  }

  static const char* value(const ::pebble::getMenu&) { return value(); }
};

template<>
struct DataType< ::pebble::getMenu > {
  static const char* value()
  {
    return "pebble/getMenu";
  }

  static const char* value(const ::pebble::getMenu&) { return value(); }
};


// service_traits::MD5Sum< ::pebble::getMenuRequest> should match 
// service_traits::MD5Sum< ::pebble::getMenu > 
template<>
struct MD5Sum< ::pebble::getMenuRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pebble::getMenu >::value();
  }
  static const char* value(const ::pebble::getMenuRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pebble::getMenuRequest> should match 
// service_traits::DataType< ::pebble::getMenu > 
template<>
struct DataType< ::pebble::getMenuRequest>
{
  static const char* value()
  {
    return DataType< ::pebble::getMenu >::value();
  }
  static const char* value(const ::pebble::getMenuRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pebble::getMenuResponse> should match 
// service_traits::MD5Sum< ::pebble::getMenu > 
template<>
struct MD5Sum< ::pebble::getMenuResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pebble::getMenu >::value();
  }
  static const char* value(const ::pebble::getMenuResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pebble::getMenuResponse> should match 
// service_traits::DataType< ::pebble::getMenu > 
template<>
struct DataType< ::pebble::getMenuResponse>
{
  static const char* value()
  {
    return DataType< ::pebble::getMenu >::value();
  }
  static const char* value(const ::pebble::getMenuResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PEBBLE_MESSAGE_GETMENU_H
