/* Auto-generated by genmsg_cpp for file /home/samer/catkin_ws/src/adc_voltage/msg/AdcVoltage.msg */
#ifndef ADC_VOLTAGE_MESSAGE_ADCVOLTAGE_H
#define ADC_VOLTAGE_MESSAGE_ADCVOLTAGE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace adc_voltage
{
template <class ContainerAllocator>
struct AdcVoltage_ {
  typedef AdcVoltage_<ContainerAllocator> Type;

  AdcVoltage_()
  : header()
  , v0(0.0)
  , v1(0.0)
  , v2(0.0)
  , v3(0.0)
  , v4(0.0)
  , v5(0.0)
  {
  }

  AdcVoltage_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , v0(0.0)
  , v1(0.0)
  , v2(0.0)
  , v3(0.0)
  , v4(0.0)
  , v5(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _v0_type;
  float v0;

  typedef float _v1_type;
  float v1;

  typedef float _v2_type;
  float v2;

  typedef float _v3_type;
  float v3;

  typedef float _v4_type;
  float v4;

  typedef float _v5_type;
  float v5;


  typedef boost::shared_ptr< ::adc_voltage::AdcVoltage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::adc_voltage::AdcVoltage_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct AdcVoltage
typedef  ::adc_voltage::AdcVoltage_<std::allocator<void> > AdcVoltage;

typedef boost::shared_ptr< ::adc_voltage::AdcVoltage> AdcVoltagePtr;
typedef boost::shared_ptr< ::adc_voltage::AdcVoltage const> AdcVoltageConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::adc_voltage::AdcVoltage_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::adc_voltage::AdcVoltage_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace adc_voltage

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::adc_voltage::AdcVoltage_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::adc_voltage::AdcVoltage_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::adc_voltage::AdcVoltage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "02c73e250b894e3099d2ca0afdf9971f";
  }

  static const char* value(const  ::adc_voltage::AdcVoltage_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x02c73e250b894e30ULL;
  static const uint64_t static_value2 = 0x99d2ca0afdf9971fULL;
};

template<class ContainerAllocator>
struct DataType< ::adc_voltage::AdcVoltage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "adc_voltage/AdcVoltage";
  }

  static const char* value(const  ::adc_voltage::AdcVoltage_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::adc_voltage::AdcVoltage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float32 v0\n\
float32 v1\n\
float32 v2\n\
float32 v3\n\
float32 v4\n\
float32 v5\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::adc_voltage::AdcVoltage_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::adc_voltage::AdcVoltage_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::adc_voltage::AdcVoltage_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::adc_voltage::AdcVoltage_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.v0);
    stream.next(m.v1);
    stream.next(m.v2);
    stream.next(m.v3);
    stream.next(m.v4);
    stream.next(m.v5);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct AdcVoltage_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::adc_voltage::AdcVoltage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::adc_voltage::AdcVoltage_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "v0: ";
    Printer<float>::stream(s, indent + "  ", v.v0);
    s << indent << "v1: ";
    Printer<float>::stream(s, indent + "  ", v.v1);
    s << indent << "v2: ";
    Printer<float>::stream(s, indent + "  ", v.v2);
    s << indent << "v3: ";
    Printer<float>::stream(s, indent + "  ", v.v3);
    s << indent << "v4: ";
    Printer<float>::stream(s, indent + "  ", v.v4);
    s << indent << "v5: ";
    Printer<float>::stream(s, indent + "  ", v.v5);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ADC_VOLTAGE_MESSAGE_ADCVOLTAGE_H

